title: Sobhan Alizadeh Offical Page
description: Data Engineer & AI Developer | Turning raw data into intelligent decisions. I architect scalable data pipelines and deploy ML models that actually work in production. Let's build something smart.
url: "https://sobhanalizadeh.github.io"
baseurl: ""

theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: Sobhan Alizadeh

# Social
social:
  name: Sobhan Alizadeh
  links:
    - https://github.com/sobhanalizadeh
    - https://www.linkedin.com/in/sobhan-alizadeh
