theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Sobhan Alizadeh Offical Page
description: Data Engineer & AI Developer | Turning raw data into intelligent decisions. I architect scalable data pipelines and deploy ML models that actually work in production. Let's build something smart.
